module.exports = (env) => ({
  '@icon-url': '"/fonts/iconfont"',
  '@primary-color': '#1783fb',
  '@btn-primary-color': '#3690f4',
  '@text-color': '#333333',
  '@primary-1': 'rgba(54, 144, 244, 0.1)',
  '@border-radius-base': '3px',
  '@border-radius-sm': '2px',
  '@shadow-color': 'rgba(0,0,0,0.05)',
  '@shadow-1-down': '4px 4px 40px @shadow-color',
  '@border-color-split': '#f4f4f4',
  '@border-color-base': '#e5e5e5',
  '@menu-dark-bg': '#3e3e3e',
  '@font-size-base': '14px',
  '@font-family': '"-apple-system", "PingFang SC", "Hiragino Sans GB", "Arial", "Microsoft YaHei", "Helvetica Neue", "sans-serif"',
});
